name: Maven publication to Artifactory

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Artifactory
      run: mvn clean deploy -s .ci.settings.xml -Drevision=0.2.$BUILD_NUMBER
